- gather_facts: false
  hosts: routers
  tasks:
  - ios_config:
      lines:
      - interface 10002
      - ip verify unicast source reachable-via rx
      - rate-limit input 1000000 187500 375000 conform-action transmit exceed-action
        drop
    name: Mitigar ataque en interface 10002 de S2.cisco.local (192.168.99.3)
  - ios_config:
      lines:
      - interface 10007
      - ip verify unicast source reachable-via rx
      - rate-limit input 1000000 187500 375000 conform-action transmit exceed-action
        drop
    name: Mitigar ataque en interface 10007 de S2.cisco.local (192.168.99.3)
